services:
  db:
    image: mysql:8.4.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u testuser -p$$MYSQL_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 50s

  
  app:
    build: .
    restart: always
    ports:
      - "4500:4500"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_USER="testuser"
      - DATABASE_PASSWORD="testpassword"
      - DATABASE_NAME="test"
      - DATABASE_HOST="db"
      - DATABASE_PORT=3306
      - DATABASE_URL="mysql://testuser:testpassword@db:3306/test"
      - PORT=4500
volumes:
  mysql_data: